{{- $existing := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "clusterstoragecontainers.serving.kserve.io" -}}
{{- if not $existing }}
{{ .Files.Get "files/serving.kserve.io_clusterstoragecontainers.yaml" }}
{{- end }}
