apiVersion: v1
kind: Service
metadata:
  name: llmisvc-webhook-server-service
  namespace: kserve
spec:
  ports:
    - name: https
      port: 443
      targetPort: webhook-server
  selector:
    control-plane: llmisvc-controller-manager
