apiVersion: v2
name: kserve-crd-minimal
version: v0.16.0
appVersion: v0.16.0
description: Helm chart for deploying minimal kserve crds without validation
type: application
keywords:
  - kserve
  - modelmesh
  - crd
  - kubernetes
  - custom-resources
home: https://kserve.github.io/website/
sources:
  - https://github.com/kserve/kserve
maintainers:
  - name: KServe Team
    url: https://github.com/kserve/kserve
icon: https://raw.githubusercontent.com/kserve/website/main/docs/images/logo.png
annotations:
  category: AI/Machine Learning
