apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kserve-tensorflow-serving.yaml
- kserve-sklearnserver.yaml
- kserve-predictiveserver.yaml
- kserve-mlserver.yaml
- kserve-xgbserver.yaml
- kserve-tritonserver.yaml
- kserve-pmmlserver.yaml
- kserve-paddleserver.yaml
- kserve-lgbserver.yaml
- kserve-torchserve.yaml
- kserve-huggingfaceserver.yaml
- kserve-huggingfaceserver-multinode.yaml

images:
  # SMS Only Runtimes
- name: tensorflow-serving
  newName: tensorflow/serving
  newTag: 2.6.2

- name: kserve-sklearnserver
  newName: kserve/sklearnserver
  newTag: v0.16.0

- name: mlserver
  newName: docker.io/seldonio/mlserver
  newTag: 1.5.0

- name: kserve-xgbserver
  newName: kserve/xgbserver
  newTag: v0.16.0

- name: kserve-tritonserver
  newName: nvcr.io/nvidia/tritonserver
  newTag: 23.05-py3

- name: kserve-pmmlserver
  newName: kserve/pmmlserver
  newTag: v0.16.0

- name: kserve-paddleserver
  newName: kserve/paddleserver
  newTag: v0.16.0

- name: kserve-lgbserver
  newName: kserve/lgbserver
  newTag: v0.16.0

- name: kserve-predictiveserver
  newName: kserve/predictiveserver
  newTag: v0.16.0
  
- name: kserve-torchserve
  newName: pytorch/torchserve-kfs
  newTag: 0.9.0

- name: huggingfaceserver
  newName: kserve/huggingfaceserver
  newTag: v0.16.0

- name: huggingfaceserver-gpu
  newName: kserve/huggingfaceserver
  newTag: v0.16.0-gpu
