apiVersion: v2
name: kserve
version: v0.16.0
appVersion: v0.16.0
description: Helm chart for deploying kserve resources
type: application
keywords:
  - kserve
  - modelmesh
  - inference
  - machine-learning
  - model-serving
home: https://kserve.github.io/website/
sources:
  - https://github.com/kserve/kserve
maintainers:
  - name: KServe Team
    url: https://github.com/kserve/kserve
icon: https://raw.githubusercontent.com/kserve/website/main/docs/images/logo.png
annotations:
  category: AI/Machine Learning
