apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: llmisvc-serving-cert
spec:
  commonName: llmisvc-webhook-server-service.{{ .Release.Namespace }}.svc
  dnsNames:
  - llmisvc-webhook-server-service.{{ .Release.Namespace }}.svc
