---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-controller-manager
  labels:
    app.kubernetes.io/name: kserve-controller-manager
    {{- if .Values.kserve.controller.labels }}
    {{- toYaml .Values.kserve.controller.labels | nindent 4 }}
    {{- end }}
  annotations:
    prometheus.io/scrape: 'true'
    {{- if .Values.kserve.controller.annotations }}
    {{- toYaml .Values.kserve.controller.annotations | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kserve-controller-manager
        {{- if .Values.kserve.controller.podLabels }}
        {{- toYaml .Values.kserve.controller.podLabels | nindent 8 }}
        {{- end }}
      {{- with .Values.kserve.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.kserve.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kserve.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kserve.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kserve.controller.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.kserve.controller.securityContext}}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: kube-rbac-proxy
        image: "{{ .Values.kserve.controller.rbacProxyImage }}"
        securityContext:
          {{- with .Values.kserve.controller.rbacProxy.securityContext}}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        resources:
          {{- with .Values.kserve.controller.rbacProxy.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      - name: manager
        image: "{{ .Values.kserve.controller.image }}:{{ .Values.kserve.controller.tag | default .Values.kserve.version }}"
        imagePullPolicy: IfNotPresent
        securityContext:
          {{- with .Values.kserve.controller.containerSecurityContext}}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        args:
        - "--metrics-addr={{ .Values.kserve.controller.metricsBindAddress }}:{{ .Values.kserve.controller.metricsBindPort }}"
        - "--leader-elect"
        resources:
{{- if .Values.kserve.controller.resources }}
{{ toYaml .Values.kserve.controller.resources | trim | indent 12 }}
{{- end }}
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
