---
apiVersion: v1
kind: Service
metadata:
  name: kserve-webhook-server-service
  {{- with .Values.kserve.controller.webhookServiceAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: kserve-controller-manager-service
  {{- with .Values.kserve.controller.serviceAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
